MkQCRes (Just False) "<log>"
"Falsifiable, after 4 tests:\n"
""
"Starting @ Ready: "
"[ (<ATMOp 'Insert ~ ()'>, CardInserted)"
", (<ATMOp 'CheckPIN 0 ~ Incorrect'>, CardInserted)"
", (<ATMOp 'CheckPIN 0 ~ Incorrect'>, CardInserted)"
", (<ATMOp 'CheckPIN 0 ~ Incorrect'>, CardInserted)"
", (<ATMOp 'CheckPIN 0 ~ Incorrect'>, CardInserted)"
"]\n"
